<?php

require_once dirname(__FILE__) . '/../../models/draft_object.php';

/**
 * Test class for draft_object.
 * Generated by PHPUnit on 2011-08-21 at 23:00:07.
 */
class draft_objectTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var draft_object
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new draft_object;
		$DBH = new PDO('mysql:host=tabby;dbname=phpdraft_test', 'phpdraft', 'mypass');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		$DBH = null;
		$this->object = null;
	}

	/**
	 * @todo Implement testGetValidity().
	 */
	public function testGetValidity() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetStatus().
	 */
	public function testGetStatus() {
		$this->object->draft_status = "undrafted";
		$this->assertTrue($this->object->getStatus() == "Setting Up");
		
		$this->object->draft_status = "in_progress";
		$this->assertTrue($this->object->getStatus() == "Currently Drafting");
		
		$this->object->draft_status = "complete";
		$this->assertTrue($this->object->getStatus() == "Draft Complete");
	}

	/**
	 * @todo Implement testGetDraftDuration().
	 */
	public function testGetDraftDuration() {
		$this->object->draft_status = "complete";
		$this->object->draft_start_time = "2011-08-20 18:52:30";
		$this->object->draft_end_time = "2011-08-20 18:59:42";
		
		$this->assertTrue($this->object->getDraftDuration() == "7 minutes, 12 seconds");
	}

	/**
	 * @todo Implement testSaveDraft().
	 */
	public function testSaveDraft() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMoveDraftForward().
	 */
	public function testMoveDraftForward() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdateStatus().
	 */
	public function testUpdateStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetupPicks().
	 */
	public function testSetupPicks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllDraftPicks().
	 */
	public function testGetAllDraftPicks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetupSport().
	 */
	public function testSetupSport() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBeginStartTime().
	 */
	public function testBeginStartTime() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteDraft().
	 */
	public function testDeleteDraft() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckDraftPublicLogin().
	 */
	public function testCheckDraftPublicLogin() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastTenPicks().
	 */
	public function testGetLastTenPicks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastFivePicks().
	 */
	public function testGetLastFivePicks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastPick().
	 */
	public function testGetLastPick() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentPick().
	 */
	public function testGetCurrentPick() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNextPick().
	 */
	public function testGetNextPick() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNextFivePicks().
	 */
	public function testGetNextFivePicks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckStatus().
	 */
	public function testCheckStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllDrafts().
	 */
	public function testGetAllDrafts() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetVisibility().
	 */
	public function testGetVisibility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsCompleted().
	 */
	public function testIsCompleted() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsUndrafted().
	 */
	public function testIsUndrafted() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsInProgress().
	 */
	public function testIsInProgress() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsPasswordProtected().
	 */
	public function testIsPasswordProtected() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStyleIsSerpentine().
	 */
	public function testStyleIsSerpentine() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStyleIsStandard().
	 */
	public function testStyleIsStandard() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
